---
name: IbexFarm

ibex_archive: "/var/l-apps/ibexfarm/ibex-beta.tar.gz"
ibex_archive_root_dir: "ibex-beta"
ibex_version: "3.0"
deployment_dir: "/var/l-apps/ibexfarm/deploy"
deployment_www_dir: "/var/l-www/ibexexps"

python_hashbang: "/opt/local/bin/python"

experiment_base_url: "http://spellout.net/ibexexps/"

db_name: ibexfarm
db_user: ibexfarm
db_host: localhost
db_port: 5432
db_password: "abcd"

config_url: "http://spellout.user.openhosting.com/ibexfarm/ajax/config"
config_permitted_hosts: ["localhost", "spellout.user.openhosting.com", "spellout.net"]

max_upload_size_bytes: 104857600000 # 1MB.

#'Plugin::Authentication':
#    default_realm: users
#    realms:
#        users:
#            credential:
#                class: Password
#                password_field: password
#                password_type: clear
#            store:
#                class: Minimal
#                users:
#                    alex:
#                        password: abcd
#                        roles: ["read"]
